import {
  errorMessage,
  gameTopicSchema,
  HTTP_ENGLISH_MESSAGES,
} from '@rapidfire/contracts';
import type { GameTopic } from '@rapidfire/contracts';
import { ApiError } from './api';

export const en = {
  skip: 'Skip to content',
  play: 'Play',
  history: 'History',
  profile: 'Profile',
  admin: 'Admin',
  championData: 'Champion data',
  championDataIntro:
    'Update the League of Legends data used to build questions.',
  championDataEmpty: 'No champion data yet',
  championDataEmptyDetail:
    'Import the latest patch to prepare the question data.',
  championDataReady: 'Data imported',
  championDataPending:
    'Question generation will be available in a later update.',
  championDataUpdate: 'Update champion data',
  championDataReimport: 'Re-import current version',
  championDataReimportHint:
    'Downloads the current patch again. Existing versions are preserved.',
  championDataPreviousSafe:
    'The current data stays available while an import runs.',
  championDataPatch: 'Patch',
  championDataLocale: 'Language',
  championDataImported: 'Imported',
  championDataChampions: 'Champions',
  championDataSkins: 'Skins',
  championDataChromas: 'Chromas',
  championDataSpells: 'Abilities',
  championDataExclusions:
    '{skins} skin chroma counts, {champions} champion chroma counts and {spells} cooldowns are unverified and excluded from those question types.',
  championDataHistory: 'Import history',
  championDataNoRuns: 'No imports have been started.',
  championDataProgress: '{done} of {total} champions saved',
  importQueued: 'Queued',
  importResolving: 'Finding the latest patch',
  importDownloading: 'Downloading champion data',
  importNormalizing: 'Checking and saving champion data',
  importPublishing: 'Finishing the import',
  importSucceeded: 'Imported',
  importUnchanged: 'Already up to date',
  importFailed: 'Import failed',
  importAborted: 'Import stopped',
  signIn: 'Sign in',
  signUp: 'Create an account',
  signOut: 'Sign out everywhere',
  homeTitle: 'Think fast. Make it count.',
  titleThink: 'Think.',
  titleAnswer: 'Answer.',
  titleGuess: 'Guess.',
  titleLearn: 'Learn.',
  titlePlay: 'Play.',
  titleWin: 'Win.',
  titleFast: 'Fast.',
  titleTagline: 'Make it count.',
  pauseTitle: 'Pause title animation',
  resumeTitle: 'Resume title animation',
  homeIntro: 'Pick a category. Trust your answer. Every second counts.',
  soloTitle: 'A round of your own',
  soloIntro:
    'Five questions per round. Play at your pace, sharpen your instincts.',
  guestName: 'Your nickname',
  startSolo: 'Start solo game',
  settings: 'Game settings',
  gameTopic: 'Game topic',
  leagueOfLegends: 'League of Legends',
  rounds: 'Rounds',
  answerTime: 'Seconds per question',
  questionsPerRound: '5 questions per round',
  availableRounds: 'Up to {rounds} rounds are available.',
  friendsTitle: 'Better with friends',
  friendsIntro: 'Create a room or enter a friend’s six-character code.',
  createRoom: 'Create a room',
  roomCode: 'Room code',
  joinRoom: 'Join room',
  friendsSignIn: 'Sign in to play with friends',
  guestNote:
    'Guest results are available until the results screen closes. Sign in before playing to keep your history.',
  accuracy: 'Accuracy first. Speed makes the difference.',
  sampleNote: 'Short rounds. Shared excitement.',
  email: 'Email address',
  password: 'Password',
  passwordConfirm: 'Confirm password',
  newPassword: 'New password',
  currentPassword: 'Current password',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  forgot: 'Forgot your password?',
  signInIntro: 'Your next round is waiting.',
  signUpIntro: 'Keep your results and play with friends.',
  noAccount: 'New to Rapidfire?',
  haveAccount: 'Already have an account?',
  nickname: 'Nickname',
  passwordHint:
    '8–128 characters with a lowercase letter, an uppercase letter, a number and a special character.',
  signupSent: 'Check your inbox',
  signupSentDetail:
    'Open the verification link, then sign in to start playing.',
  resend: 'Resend verification email',
  resendWait: 'You can request another email in {seconds} seconds.',
  forgotTitle: 'Reset your password',
  forgotIntro: 'Enter your email address to request a recovery link.',
  sendReset: 'Send recovery link',
  resetTitle: 'Choose a new password',
  resetIntro:
    'Your recovery link is valid for 15 minutes and can be used once.',
  savePassword: 'Save new password',
  resetDone: 'Password updated. Sign in with your new password.',
  missingToken: 'This recovery link is incomplete. Request a new link.',
  verified: 'Email verified',
  verifiedDetail: 'You can now sign in and play.',
  verificationFailed:
    'This verification link is invalid or has expired. Request a new email.',
  back: 'Back to play',
  loading: 'Loading…',
  saving: 'Saving…',
  working: 'Working…',
  connecting: 'Connecting…',
  reconnecting: 'Connection lost. Reconnecting…',
  retry: 'Try again',
  connectionReady: 'Connected',
  connectionFailed: 'Unable to connect. Check your connection and try again.',
  unknownOutcome:
    'No confirmation received. The action may have succeeded. Reconnect to check before trying again.',
  invalidResponse:
    'The server sent an unexpected response. Refresh the page and try again.',
  networkError:
    'Unable to reach the server. Check your connection and try again.',
  refresh: 'Refresh the page',
  dismiss: 'Dismiss message',
  lobby: 'Your room',
  lobbyIntro:
    'Share the code, get ready, and the game starts when everyone is ready.',
  copyCode: 'Copy room code',
  copied: 'Room code copied.',
  copyFailed: 'Select and copy the room code to share it.',
  players: 'Players',
  you: 'You',
  owner: 'Host',
  ready: 'Ready',
  notReady: 'Not ready',
  offline: 'Offline',
  authenticationRequired: 'Sign in again',
  grace: '{seconds}s remaining',
  readyButton: 'I’m ready',
  cancelReady: 'Not ready yet',
  waitingPlayers: 'Waiting for everyone to get ready.',
  starting: 'Game starts in',
  updateSettings: 'Save game settings',
  settingsSaved: 'Settings updated. Everyone needs to get ready again.',
  leaveRoom: 'Leave room',
  leaveGame: 'Leave game',
  leaveTitle: 'Leave this game?',
  leaveDetail:
    'You will leave on every device. An answer already accepted will still be scored.',
  leaveRoomDetail: 'You will leave the room on every device.',
  stay: 'Stay here',
  leave: 'Leave',
  categoryTitle: 'Choose the next category',
  categoryWaiting: '{name} is choosing the category.',
  categoryAuto: 'The game will choose a category.',
  categoryHint: 'One category. Five questions. Make it yours.',
  preparing: 'Preparing your questions…',
  getReady: 'Get ready',
  question: 'Question {number} of 5',
  round: 'Round {number} of {total}',
  timeLeft: 'Time remaining',
  seconds: '{seconds}s',
  selectOne: 'Choose one answer. Your choice is submitted immediately.',
  selectMany: 'Choose all answers you think are correct',
  lockAnswer: 'Lock in answer',
  answerLocked: 'Answer locked on every device',
  answerPending: 'Confirming your answer…',
  awaitingResults: 'Waiting for results',
  timeUp: 'Time is up',
  nextQuestion: 'Next question in',
  answered: 'Answered',
  idle: 'Idle',
  left: 'Left',
  deletedUser: 'Deleted user',
  score: 'Score',
  points: '{points} points',
  resultCorrect: 'Correct',
  resultIncorrect: 'Incorrect',
  resultPartial: '{selected} of {total} correct',
  resultUnanswered: 'No answer',
  correctAnswer: 'Correct answer',
  yourAnswer: 'Your answer',
  chooseCategory: 'Choose {category}',
  results: 'Round complete',
  resultsTitle: 'Game complete',
  resultIntro: 'Here’s how everyone finished.',
  yourScore: 'Your final score',
  yourAnswers: 'Your answers',
  place: 'Place',
  returning: 'Returning in {seconds}s',
  guestSave:
    'Sign in before your next game to save your results. This guest game cannot be added later.',
  signInNext: 'Sign in for your next game',
  resultHistory: 'Results saved to your history.',
  interrupted: 'Game interrupted',
  noResult: 'There is no result for this question.',
  authExpired:
    'Your session has expired. You can finish this game; sign in again before your next one.',
  lobbyAuth:
    'Sign in again within the remaining time to keep your place. Ready stays off until you return.',
  profileIntro: 'Your name at the table.',
  elo: 'ELO',
  eloHint:
    'Everyone starts at 1000. Ranked play is planned for a later release.',
  saveProfile: 'Save nickname',
  profileSaved: 'Nickname updated.',
  security: 'Account security',
  changePassword: 'Change password',
  passwordChanged: 'Password updated. Sign in again on your devices.',
  deleteAccount: 'Delete account',
  deleteTitle: 'Delete your account permanently?',
  deleteDetail:
    'Your profile and solo results will be deleted. Your name in shared results will become “Deleted user”. This cannot be undone.',
  confirmDelete: 'Delete permanently',
  accountDeleted: 'Your account has been deleted.',
  historyTitle: 'Your rounds, remembered',
  historyIntro: 'Your saved games and a question-by-question recap.',
  historyEmpty: 'Your first result starts here.',
  historyEmptyDetail:
    'Play a game while signed in and your result will appear here.',
  historyMore: 'Load more games',
  viewGame: 'View game',
  gameDetail: 'Game result',
  completed: 'Completed',
  inProgress: 'In progress',
  interruptedStatus: 'Interrupted',
  solo: 'Solo',
  multiplayer: 'With friends',
  roundSettings: 'Rounds: {rounds} · {seconds}s per question',
  notFound: 'This page is not available.',
  noAccess: 'Sign in to view your profile and saved results.',
  checkFields: 'Check the highlighted fields.',
  required: 'Enter a value for this field.',
  invalidEmail: 'Enter a valid email address.',
  invalidNickname: 'Use between 1 and 40 characters.',
  invalidSettings: 'Use 1–{rounds} rounds and 5–60 seconds per question.',
  invalidCode: 'Enter the six-character room code.',
  notSavedGuest: 'Sign in before your next game to save your results.',
  persistencePending: 'Saving results…',
  persistenceRetrying: 'Retrying result storage…',
  persistenceFailed: 'Results could not be saved to your history.',
  persistenceUnavailable: 'Result storage is not available.',
  closedLeft: 'You left the game on every device.',
  closedRoomDeleted: 'The room has closed.',
  closedOffline: 'Your place was released after one minute offline.',
  closedAuth: 'Your place was released because sign-in was not renewed.',
  closedRevoked: 'Your access ended. Sign in again to play.',
  reconnect: 'Reconnect',
  sync: 'Check current game state',
  unsaved: 'Discard your unsaved changes?',
  questionSummary: 'Round {round}, question {question}',
  joined: 'Joined the room.',
  sessionUnavailable:
    'Unable to check your session. Your current game can continue.',
  noActiveGame: 'There is no active game to return to.',
  guest: 'Guest',
} as const;
export type CopyKey = keyof typeof en;
export function t(
  key: CopyKey,
  params: Readonly<Record<string, string | number>> = {},
): string {
  return Object.entries(params).reduce(
    (message, [name, value]) => message.replaceAll(`{${name}}`, String(value)),
    String(en[key]),
  );
}
export function message(error: unknown): string {
  if (!(error instanceof ApiError)) return t('networkError');
  if (error.code === 'NETWORK_ERROR') return t('networkError');
  if (error.code === 'INVALID_RESPONSE') return t('invalidResponse');
  if (error.code === 'ACK_TIMEOUT') return t('unknownOutcome');
  if (Object.hasOwn(HTTP_ENGLISH_MESSAGES, error.code)) {
    const entry = Object.entries(HTTP_ENGLISH_MESSAGES).find(
      ([key]) => key === error.code,
    );
    if (entry) return entry[1];
  }
  return errorMessage(error.code);
}
export const numbers = new Intl.NumberFormat('en');
const topicCopy = {
  'league-of-legends': 'leagueOfLegends',
} as const satisfies Record<GameTopic, keyof typeof en>;
export function topicName(topicId: string): string {
  const topic = gameTopicSchema.safeParse(topicId);
  return topic.success ? t(topicCopy[topic.data]) : topicId;
}
export const dates = new Intl.DateTimeFormat('en', {
  dateStyle: 'medium',
  timeStyle: 'short',
});
